// Single source of truth for white-labeling.
// Change values here to re-skin for a new client.

import { 
  Compass, Feather, Flame, Leaf, 
  Home, KeyRound, Lamp, Hammer, Building2, Sparkles,
  ClipboardList, Pencil, HardHat
} from "lucide-react";

export const site = {
  studio: {
    name: "Naksha & Nivriti",
    short: "Naksha & Nivriti",
    logo: "/logo.png",
    tagline: "Structural luxury interiors and styling for modern Indian homes.",
    legalName: "Naksha & Nivriti by Divyani & Yogini",
    foundedYear: 2021,
    yearsExperience: new Date().getFullYear() - 2021,
    city: "Pune",
    serviceCities: ["Pune", "Chandrapur", "Maharashtra"],
    address: {
      street: "Pune & Chandrapur",
      city: "Pune",
      state: "Maharashtra",
      pin: "",
      country: "India",
    },
    contact: {
      phoneDisplay: "+91 83788 41603",
      phoneE164: "+918378841603",
      whatsappE164: "918378841603",
      whatsappPrefill:
        "Hello Naksha & Nivriti, I would like to discuss my dream home interiors.",
      email: "teamnakshaandnivriti@gmail.com",
      hours: "Mon – Sat · 10:00 – 19:00 IST",
    },
    socials: {
      instagram: "https://instagram.com/naksha_and_nivriti",
      pinterest: "#",
      youtube: "#",
      linkedin: "#",
    },
    seo: {
      domain: "https://nakshaandnivriti.com",
      title: "Naksha & Nivriti · Luxury Interior Designers in Pune",
      description:
        "Naksha & Nivriti creates structural luxury interiors, styling, and complete home solutions for modern homes across Pune and Chandrapur.",
      keywords: [
        "interior designer pune",
        "luxury interiors pune",
        "naksha and nivriti",
        "interior designer chandrapur",
        "complete home solutions",
        "structural luxury interiors",
      ],
    },
  },
  hero: {
    titleLines: ["Luxury Interiors", "Complete Home Solutions for"],
    titleAccent: "Modern India",
    sub:
      "Naksha & Nivriti creates elegant, functional, and luxury interiors with structural planning, styling, and execution under one roof.",
    primaryCta: { label: "Book a Consultation", href: "#contact" },
    secondaryCta: { label: "View the Portfolio", href: "#portfolio" },
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=2400&q=80",
  },
  stats: [
    { value: 24, suffix: "+", label: "Projects & Posts" },
    { value: 1800, suffix: "+", label: "Instagram Community" },
    { value: 2, suffix: "", label: "Founder-Led Studio" },
    { value: 100, suffix: "%", label: "Design Focus" },
  ],
  philosophy: {
    eyebrow: "Our Philosophy",
    title: "Homes that feel luxurious, practical, and deeply personal.",
    image: "https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?auto=format&fit=crop&w=1600&q=80",
    pillars: [
      {
        icon: Compass,
        title: "Structural Planning",
        desc: "We plan layouts, circulation, and functionality before styling the space beautifully.",
      },
      {
        icon: Feather,
        title: "Luxury Styling",
        desc: "Every wall, light, texture, and detail is selected to create a premium yet warm home.",
      },
      {
        icon: Flame,
        title: "Execution Detailing",
        desc: "From site work to finishing, every detail is monitored so the final output feels refined.",
      },
      {
        icon: Leaf,
        title: "Budget-Smart Design",
        desc: "We make spaces look luxurious without wasting money on unnecessary additions.",
      },
    ],
  },
  services: {
    eyebrow: "Our Practice",
    title: "Complete home solutions in one roof.",
    sub: "We bring structure, luxury interiors, styling, renovation, and execution together so your home feels beautiful and practical from day one.",
    list: [
      {
        no: "01",
        icon: Home,
        title: "Full-Home Interiors",
        span: "From empty shell to dream home",
        desc: "End-to-end interior design and execution for apartments, villas, and family homes.",
        bullets: ["Space planning", "Furniture layout", "Complete execution"],
        img: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=80",
      },
      {
        no: "02",
        icon: KeyRound,
        title: "Modular Kitchens",
        span: "Smart storage with premium finishes",
        desc: "Functional kitchen designs made for Indian homes, daily cooking, and easy movement.",
        bullets: ["Modular layouts", "Practical storage", "Premium finishes"],
        img: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1600&q=80",
      },
      {
        no: "03",
        icon: Lamp,
        title: "Luxury Styling",
        span: "The details that make a space feel complete",
        desc: "Lighting, wall treatments, decor, textures, and soft styling for a polished luxury look.",
        bullets: ["Lighting design", "Wall concepts", "Decor styling"],
        img: "https://images.unsplash.com/photo-1567016526105-22da7c13161a?auto=format&fit=crop&w=1600&q=80",
      },
      {
        no: "04",
        icon: Hammer,
        title: "Renovations & Makeovers",
        span: "Transform old spaces into fresh luxury interiors",
        desc: "Room makeovers, TV units, false ceilings, wall upgrades, and complete renovation work.",
        bullets: ["Before-after makeovers", "TV unit redesign", "Budget-friendly upgrades"],
        img: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1600&q=80",
      },
      {
        no: "05",
        icon: Building2,
        title: "Commercial Interiors",
        span: "Professional spaces with strong first impressions",
        desc: "Design solutions for offices, studios, clinics, retail spaces, and commercial projects.",
        bullets: ["Brand-focused layouts", "Practical planning", "Premium presentation"],
        img: "https://images.unsplash.com/photo-1564540583246-934409427776?auto=format&fit=crop&w=1600&q=80",
      },
      {
        no: "06",
        icon: Sparkles,
        title: "Custom Furniture & Decor",
        span: "Made-to-fit pieces for your exact space",
        desc: "Customized furniture, storage units, decor pieces, and statement elements for your home.",
        bullets: ["Custom units", "Material selection", "Detail-focused finishing"],
        img: "https://images.unsplash.com/photo-1532372576444-dda954194ad0?auto=format&fit=crop&w=1600&q=80",
      },
    ],
  },
  portfolio: {
    eyebrow: "Selected Work",
    title: "Spaces designed with emotion, structure, and precision.",
    sub: "A curated look at luxury homes, transformations, styling moments, and modern residential interiors.",
    note: "More walkthroughs, site videos, and complete project details are shared during your consultation.",
    filters: ["All", "Residence", "Bedroom", "Renovation", "Luxury", "Commercial"],
    projects: [
      {
        title: "Luxury TV Unit Transformation",
        city: "Pune",
        category: "Renovation",
        scope: "Living room · TV wall",
        area: "450 sq ft",
        year: 2026,
        img: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80",
        span: "wide",
      },
      {
        title: "Modern Bedroom Concept",
        city: "Pune",
        category: "Bedroom",
        scope: "Luxury bedroom design",
        area: "320 sq ft",
        year: 2026,
        img: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80",
        span: "square",
      },
      {
        title: "Complete Home Styling",
        city: "Chandrapur",
        category: "Residence",
        scope: "Full home interiors",
        area: "1,800 sq ft",
        year: 2025,
        img: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80",
        span: "tall",
      },
      {
        title: "Elegant Entrance Door",
        city: "Maharashtra",
        category: "Luxury",
        scope: "Entrance styling",
        area: "120 sq ft",
        year: 2025,
        img: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1600&q=80",
        span: "square",
      },
      {
        title: "Luxury Wall & Lighting",
        city: "Pune",
        category: "Residence",
        scope: "Feature wall design",
        area: "260 sq ft",
        year: 2025,
        img: "https://images.unsplash.com/photo-1567016526105-22da7c13161a?auto=format&fit=crop&w=1600&q=80",
        span: "tall",
      },
      {
        title: "Structural Design Planning",
        city: "Chandrapur",
        category: "Commercial",
        scope: "Planning + interiors",
        area: "2,000 sq ft",
        year: 2025,
        img: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1600&q=80",
        span: "wide",
      },
    ],
  },
  beforeAfter: {
    eyebrow: "Before & After",
    titleLines: ["Ordinary walls.", "A luxury transformation."],
    sub: "Drag the handle to reveal how thoughtful planning, lighting, and detailing can completely change a space.",
    cases: [
      {
        title: "Living Room TV Unit",
        location: "Pune",
        days: 45,
        before: "https://images.unsplash.com/photo-1583845112203-29329902332e?auto=format&fit=crop&w=1800&q=80",
        after: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1800&q=80",
        note: "A simple wall upgraded into a premium living room focal point.",
      },
      {
        title: "Modern Bedroom Makeover",
        location: "Chandrapur",
        days: 60,
        before: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1800&q=80",
        after: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1800&q=80",
        note: "A practical bedroom redesigned with comfort, lighting, and luxury finishes.",
      },
    ],
  },
  process: {
    eyebrow: "From Idea to Handover",
    title: "A clear design process for stress-free interiors.",
    sub: "Every project begins with understanding your lifestyle, budget, space, and dream outcome before moving into design and execution.",
    steps: [
      {
        n: "01",
        icon: ClipboardList,
        title: "Discovery Call",
        weeks: "Step 1",
        body: "We understand your home, requirements, lifestyle, budget, and the kind of space you want to create.",
      },
      {
        n: "02",
        icon: Pencil,
        title: "Concept & Planning",
        weeks: "Step 2",
        body: "Layouts, mood boards, material direction, and design concepts are created for your approval.",
      },
      {
        n: "03",
        icon: Sparkles,
        title: "Material & Styling",
        weeks: "Step 3",
        body: "We select finishes, lighting, furniture, colors, textures, and decor elements for a complete look.",
      },
      {
        n: "04",
        icon: HardHat,
        title: "Site Execution",
        weeks: "Step 4",
        body: "The design is executed on-site with proper supervision, detailing, and quality checks.",
      },
      {
        n: "05",
        icon: Home,
        title: "Final Handover",
        weeks: "Step 5",
        body: "Final styling, cleaning, checks, and handover are completed so your space feels ready to live in.",
      },
    ],
  },
  testimonials: [
    {
      quote: "Naksha & Nivriti made our home feel premium, warm, and practical at the same time.",
      author: "Residential Client",
      location: "Pune",
    },
    {
      quote: "Their sense of styling, lighting, and detailing completely changed the look of our space.",
      author: "Homeowner",
      location: "Chandrapur",
    },
    {
      quote: "They understand how to create a luxury look without making the design feel overdone.",
      author: "Apartment Owner",
      location: "Maharashtra",
    },
    {
      quote: "From planning to execution, the process felt personal, clear, and professionally handled.",
      author: "Interior Project Client",
      location: "Pune",
    },
  ],
  faq: [
    {
      q: "Do you provide complete home solutions?",
      a: "Yes. Naksha & Nivriti offers structural planning, interiors, styling, renovation, and execution support under one roof.",
    },
    {
      q: "Which cities do you serve?",
      a: "We primarily serve Pune, Chandrapur, and nearby cities in Maharashtra.",
    },
    {
      q: "Can you design within a limited budget?",
      a: "Yes. We focus on budget-smart design so your home looks premium without unnecessary overspending.",
    },
  ],
};

export type SiteConfig = typeof site;
