// Single source of truth for white-labeling.
// Change values here to re-skin for a new client.

import { 
  Compass, Feather, Flame, Leaf, 
  Home, KeyRound, Lamp, Hammer, Building2, Sparkles,
  ClipboardList, Pencil, HardHat
} from "lucide-react";

export const site = {
  studio: {
    name: "Purple Patch Interior Designer",
    short: "Purple Patch",
    logo: "/logo.png",
    tagline: "Pocket-friendly, professional, and beautifully crafted interiors.",
    legalName: "Purple Patch Interior Designer n Planner",
    foundedYear: 2015,
    yearsExperience: new Date().getFullYear() - 2015,
    city: "Gwalior",
    serviceCities: ["Gwalior", "Madhya Pradesh", "Delhi NCR"],
    address: {
      street: "3rd floor, Rajeev Plaza, near SKS new, Jayendraganj, Shinde Ki Chhawani",
      city: "Gwalior",
      state: "Madhya Pradesh",
      pin: "474001",
      country: "India",
    },
    contact: {
      phoneDisplay: "+91 98262 43120",
      phoneE164: "+919826243120",
      whatsappE164: "919826243120",
      whatsappPrefill:
        "Hello Atul ji, I would like to discuss an interior design project for my home.",
      email: "studio@purplepatch.design",
      hours: "Mon – Sat · 10:00 – 19:30 IST",
    },
    socials: {
      instagram: "https://instagram.com/purplepatch",
      pinterest: "https://pinterest.com/purplepatch",
      youtube: "https://youtube.com/@purplepatch",
      linkedin: "https://linkedin.com/company/purplepatch",
    },
    seo: {
      domain: "https://purplepatch.design",
      title: "Purple Patch Interior Designer · Best in Gwalior",
      description:
        "Top-rated interior designer in Gwalior led by Atul Shrivastava. We deliver beautiful, comforting, and pocket-friendly dream homes on time with superior quality.",
      keywords: [
        "interior designer gwalior",
        "best interior designer madhya pradesh",
        "atul shrivastava",
        "pocket friendly interior design",
        "commercial interior design gwalior",
      ],
    },
  },
  hero: {
    titleLines: ["Beautiful Homes", "Comforting Interiors for"],
    titleAccent: "Modern India",
    sub:
      "We are the top-rated interior design studio in Gwalior. Led by Atul Shrivastava, we design and build premium, pocket-friendly homes with a personal touch.",
    primaryCta: { label: "Book a Consultation", href: "#contact" },
    secondaryCta: { label: "View the Portfolio", href: "#portfolio" },
    image: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=2400&q=80",
  },
  stats: [
    { value: 67, suffix: "+", label: "5-Star Reviews" },
    { value: 4.9, suffix: "/5", label: "Google Rating" },
    { value: 99, suffix: "%", label: "On time" },
    { value: 100, suffix: "%", label: "Quality Assured" },
  ],
  philosophy: {
    eyebrow: "Our Philosophy",
    title: "Beautiful spaces, crafted with a personal touch.",
    image: "https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?auto=format&fit=crop&w=1600&q=80",
    pillars: [
      {
        icon: Compass,
        title: "Proper Space Utilization",
        desc: "Well-planned interiors that maximize every inch of your space without feeling cluttered.",
      },
      {
        icon: Feather,
        title: "Comfort & Positivity",
        desc: "We design homes that radiate positive vibes and offer genuine comfort in every corner.",
      },
      {
        icon: Flame,
        title: "Timely Execution",
        desc: "We believe in respecting your time. Our projects are completed accurately and on schedule.",
      },
      {
        icon: Leaf,
        title: "Pocket-Friendly Quality",
        desc: "We deliver superior quality exterior and interior work at prices that respect your budget.",
      },
    ],
  },
  services: {
    eyebrow: "Our Practice",
    title: "Six disciplines, one signature.",
    sub: "We work end-to-end so the seam between civil work, joinery, lighting, and styling disappears. One contract. One conscience. One key on the day of handover.",
    list: [
      {
        no: "01",
        icon: Home,
        title: "Full-Home Residences",
        span: "From the master plan to the last brass switch plate",
        desc: "End-to-end design and project delivery for apartments, villas and penthouses.",
        bullets: ["Architecture-grade drawings", "146 quality checkpoints", "Lifetime warranty on joinery"],
        img: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=80",
      },
      {
        no: "02",
        icon: KeyRound,
        title: "Modular Kitchens",
        span: "European hardware, Indian sensibility",
        desc: "Engineered cabinetry built in our own factory with BWP marine ply.",
        bullets: ["7-year on-site warranty", "ISI-certified ply only", "Designed for Indian cooking"],
        img: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1600&q=80",
      },
      {
        no: "03",
        icon: Lamp,
        title: "Lighting & Styling",
        span: "Light-first interiors that age gracefully",
        desc: "Architectural lighting plans and slow curation of art and artifacts.",
        bullets: ["3-layer lighting design", "Curated artwork sourcing", "Soft launch styling visit"],
        img: "https://images.unsplash.com/photo-1567016526105-22da7c13161a?auto=format&fit=crop&w=1600&q=80",
      },
      {
        no: "04",
        icon: Hammer,
        title: "Renovations & Reset",
        span: "Quiet upgrades for the home you already love",
        desc: "Refresh single rooms or whole floors without the chaos. Live-in execution.",
        bullets: ["Dust-controlled site", "Live-in execution", "Fixed-price commitment"],
        img: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1600&q=80",
      },
      {
        no: "05",
        icon: Building2,
        title: "Hospitality & Retail",
        span: "Spaces that turn a transaction into a memory",
        desc: "Restaurants, boutique hotels, flagship stores. Brand-coherent interiors.",
        bullets: ["Concept-to-handover", "Brand-grade detailing", "Operations-ready FF&E"],
        img: "https://images.unsplash.com/photo-1564540583246-934409427776?auto=format&fit=crop&w=1600&q=80",
      },
      {
        no: "06",
        icon: Sparkles,
        title: "Bespoke Furniture",
        span: "One-off pieces, made to outlast",
        desc: "Designed in studio, hand-finished by master karigars across India.",
        bullets: ["Solid teak / marine ply", "Hand-rubbed finishes", "Three-month lead time"],
        img: "https://images.unsplash.com/photo-1532372576444-dda954194ad0?auto=format&fit=crop&w=1600&q=80",
      },
    ],
  },
  portfolio: {
    eyebrow: "Selected Work",
    title: "Nine homes, one quiet language.",
    sub: "A curated cross-section of recent residences and ateliers. Each project sits at least eighteen months from first conversation to handover.",
    note: "A more complete book of work is shared during your private consultation.",
    filters: ["All", "Residence", "Villa", "Penthouse", "Hospitality", "Boutique"],
    projects: [
      {
        title: "House of Jasmine",
        city: "Bandra, Mumbai",
        category: "Residence",
        scope: "Full home · 4 BHK",
        area: "3,200 sq ft",
        year: 2025,
        img: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1600&q=80",
        span: "tall",
      },
      {
        title: "The Quiet Penthouse",
        city: "Worli, Mumbai",
        category: "Penthouse",
        scope: "Full home · 5 BHK",
        area: "6,800 sq ft",
        year: 2025,
        img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
        span: "wide",
      },
      {
        title: "Lake Villa No. 4",
        city: "Sarjapur, Bengaluru",
        category: "Villa",
        scope: "Architecture + interiors",
        area: "9,400 sq ft",
        year: 2024,
        img: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1600&q=80",
        span: "square",
      },
      {
        title: "Athangudi House",
        city: "Karaikudi, Chettinad",
        category: "Residence",
        scope: "Heritage restoration",
        area: "7,200 sq ft",
        year: 2024,
        img: "https://images.unsplash.com/photo-1616137422495-1e9e46e2aa77?auto=format&fit=crop&w=1600&q=80",
        span: "square",
      },
      {
        title: "Iris & Marigold",
        city: "Vasant Vihar, Delhi",
        category: "Residence",
        scope: "Full home · 3 BHK",
        area: "2,400 sq ft",
        year: 2025,
        img: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1600&q=80",
        span: "tall",
      },
      {
        title: "Soma Café & Bar",
        city: "Khan Market, Delhi",
        category: "Hospitality",
        scope: "Restaurant",
        area: "3,800 sq ft",
        year: 2024,
        img: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?auto=format&fit=crop&w=1600&q=80",
        span: "wide",
      },
      {
        title: "Karigar Atelier",
        city: "Jaipur",
        category: "Boutique",
        scope: "Flagship retail",
        area: "1,900 sq ft",
        year: 2024,
        img: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80",
        span: "square",
      },
      {
        title: "Casa Banyan",
        city: "Aldona, Goa",
        category: "Villa",
        scope: "Holiday villa",
        area: "5,600 sq ft",
        year: 2023,
        img: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=80",
        span: "square",
      },
      {
        title: "Sea House",
        city: "Juhu, Mumbai",
        category: "Penthouse",
        scope: "Full home · 4 BHK",
        area: "5,100 sq ft",
        year: 2023,
        img: "https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1600&q=80",
        span: "wide",
      },
    ],
  },
  beforeAfter: {
    eyebrow: "Before & After",
    titleLines: ["The same four walls.", "Twelve weeks apart."],
    sub: "Drag the brass handle to reveal the transformation. Every project below was completed inside its committed timeline.",
    cases: [
      {
        title: "House of Jasmine — Living",
        location: "Bandra, Mumbai",
        days: 84,
        before: "https://images.unsplash.com/photo-1583845112203-29329902332e?auto=format&fit=crop&w=1800&q=80",
        after: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1800&q=80",
        note: "From the developer-handover shell to a layered living room.",
      },
      {
        title: "Lake Villa No. 4 — Kitchen",
        location: "Sarjapur, Bengaluru",
        days: 112,
        before: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1800&q=80",
        after: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1800&q=80",
        note: "Re-planned for an Indian-cooking household.",
      },
    ],
  },
  process: {
    eyebrow: "From Brief to Handover",
    title: "A studio process, not a sales process.",
    sub: "Twenty-four to thirty-six weeks for a residence, depending on civil scope. Fixed fee. No hidden economics.",
    steps: [
      {
        n: "01",
        icon: ClipboardList,
        title: "The Listening",
        weeks: "Week 1 – 2",
        body: "A long, unrushed conversation to map your routines, rituals, and the silent non-negotiables.",
      },
      {
        n: "02",
        icon: Pencil,
        title: "Concept & Drawings",
        weeks: "Week 3 – 6",
        body: "A bound brief, mood narrative, scaled plans, elevations, and 3-dimensional walkthroughs.",
      },
      {
        n: "03",
        icon: Sparkles,
        title: "Material Library",
        weeks: "Week 7 – 9",
        body: "A physical library is built — stones, woods, fabrics — and lived with for two weeks.",
      },
      {
        n: "04",
        icon: HardHat,
        title: "Site & Joinery",
        weeks: "Week 10 – 26",
        body: "On-site supervision six days a week, joinery in our partner ateliers.",
      },
      {
        n: "05",
        icon: Home,
        title: "Styling & Handover",
        weeks: "Week 27 – 30",
        body: "Art, books, linens, scent — the last 5%. We hand over a home that's already lived-in.",
      },
    ],
  },
  testimonials: [
    {
      quote: "The best interior designer in town. Undoubtedly. An extremely humble yet professional person—Mr Atul Shrivastava, is the best in his field in Gwalior.",
      author: "Dr. Sanyukta Bargale",
      location: "Shrivastava Dental Clinic, Gwalior",
    },
    {
      quote: "Truly the best in Gwalior. I have gotten the interiors of my workplace 3 times and at my home done by Atul ji and each project has received great appreciation. His sense of design is so refreshing that it never feels boring.",
      author: "Akarshan Asha",
      location: "Gwalior, Madhya Pradesh",
    },
    {
      quote: "Purple patch interior and Mr Atul ji made my home the dream home I can ever imagine. Home with positive vibes, peace in every corner, beautifully crafted with a personal touch.",
      author: "Deepti Jain",
      location: "Gwalior, Madhya Pradesh",
    },
    {
      quote: "Very professional, on time, good selection, and very soft spoken. In single word 'Fabulous, Fantastic, unimaginable'.",
      author: "Sparsh Health Care",
      location: "Commercial Project, Gwalior",
    },
  ],
  faq: [
    {
      q: "How long does a full-home interior take?",
      a: "A typical 3 BHK runs 18 – 24 weeks. Villas with civil scope run 28 – 36 weeks.",
    },
    {
      q: "Are you Vastu compliant?",
      a: "Yes, fully. We work with senior Vastu pandits when it's part of your brief.",
    },
    {
      q: "How do you protect our privacy?",
      a: "Every engagement is under NDA. Your home is photographed only with your permission.",
    },
  ],
};

export type SiteConfig = typeof site;
